# Generated by Django 4.1.2 on 2023-04-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_category_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_active',
            new_name='display_home',
        ),
    ]
