# Generated by Django 4.1.2 on 2023-04-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_importorder_supplier_alter_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importorder',
            old_name='date',
            new_name='date_created_at',
        ),
    ]
