# Generated by Django 4.1.2 on 2023-04-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_rename_date_importorder_date_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./static/images/brand'),
        ),
    ]
