# Generated by Django 4.1.2 on 2023-04-23 20:01

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_alter_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='brand'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product'),
        ),
    ]
