# Generated by Django 4.1.2 on 2023-05-02 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_alter_brand_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importorderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product'),
        ),
    ]
