# Generated by Django 4.1.2 on 2023-05-02 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_instrumenttype_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30, null=True)),
                ('customer_phone', models.CharField(max_length=11, null=True)),
                ('ordered_time', models.DateTimeField(auto_now_add=True)),
                ('confirmed_time', models.DateTimeField(blank=True, null=True)),
                ('shipped_time', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('DELIVERING', 'Đang giao'), ('DELIVERED', 'Đã giao')], max_length=20)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='importorder',
            name='date_created_at',
        ),
        migrations.RemoveField(
            model_name='importorderitem',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='importorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='importorder',
            name='supplier_phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='importorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='importorderitem',
            name='import_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_order_items', to='ecommerce.importorder'),
        ),
        migrations.AlterField(
            model_name='importorder',
            name='supplier_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importorderitem',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='ecommerce.purchaseorder')),
            ],
        ),
    ]
