# Generated by Django 4.1.2 on 2023-05-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_purchaseorder_remove_importorder_date_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importorder',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='importorder',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.supplier'),
        ),
    ]
