# Generated by Django 4.1.2 on 2023-05-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_alter_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('DELIVERING', 'Đang giao'), ('DELIVERED', 'Đã giao'), ('CANCELED', 'Đã hủy')], max_length=20),
        ),
    ]
