# Generated by Django 4.1.2 on 2023-05-16 21:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0033_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='static/images/brand'),
        ),
    ]
