# Generated by Django 4.1.2 on 2023-05-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0036_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
