# Generated by Django 4.1.2 on 2023-05-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0037_purchaseorder_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='receiver_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='receiver_phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
