# Generated by Django 4.1.2 on 2023-05-18 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0038_purchaseorder_receiver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importorderitem',
            name='import_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.importorder'),
        ),
    ]
