# Generated by Django 4.1.2 on 2023-05-18 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_alter_importorderitem_import_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importorderitem',
            name='import_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_order_items', to='ecommerce.importorder'),
        ),
    ]
